# EXAMPLE USAGE:
#
#   Refer for explanation to following link:
#   https://github.com/evilmartians/lefthook/blob/master/docs/configuration.md
#
pre-commit:
  commands:
    yaml-lint:
      run: |
        prettier --write action.yml
        yamllint action.yml