---
name: "EPFL ENAC-IT4R Build Publish and Deploy"
description: >
  This action builds, publishes and deploys an application to the EPFL-ENAC
  IT4R platform, which is a Kubernetes cluster. It is a composite action that
  uses the docker/metadata-action, docker/build-push-action and a custom
  curl-based deployment action. using a github dispatch event.
inputs:
  # CD_URI: https://api.github.com/repos/EPFL-ENAC/enack8s-app-config/dispatches
  ENAC_IT4R_CD_ORG:
    description: >
      App deployment org: examples are epfl-enac, epfl-lasur, epfl-resslab
    required: true
  ENAC_IT4R_CD_REPO:
    description: >
      Deployment app repo: examples are resslab-astra-82001-frontend, which corresponds
      to the frontend of the Astra 82001 project in the resslab org situated
      in the EPFL-ENAC/enack8s-app-config/epfl-resslab/resslab-astra-82001-frontend
    required: true
  ENAC_IT4R_CD_TOKEN:
    description: >
      App deployment secret given by the IT4R team enacit4research@epfl.ch
    required: true
  ENAC_IT4R_CD_BUILD_CONTEXT:
    description: >
      The context of the build, e.g. a list of directory paths to include
      in the build where the Dockerfile is located, for instances:
      ["./backend", "./admin", "./frontend"], default is ["./"]
      cf readme.md for more information
    required: false
    default: '["./"]'
runs:
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Call deploy.yml
      uses: "./.github/workflows/deploy.yml"
      uses:  EPFL-ENAC/epfl-enac-build-push-deploy-action/deploy.yml@main
      with:
        org: ${{ inputs.ENAC_IT4R_CD_ORG }}
        repo: ${{ inputs.ENAC_IT4R_CD_REPO }}
        build_context: ${{ inputs.ENAC_IT4R_CD_BUILD_CONTEXT }}
        token: ${{ inputs.ENAC_IT4R_CD_TOKEN }}
