---
name: "EPFL ENAC-IT4R Deploy"
description: "EPFL ENAC-IT4R Deployment"
inputs:
  ENAC_IT4R_CD_environment:
    description: "Deployment environment"
    required: true
  ENAC_IT4R_CD_deployment_id:
    description: "App deployment ID"
    required: true
  ENAC_IT4R_CD_deployment_secret:
    description: "App deployment secret"
    required: true
  interval:
    description: "Polling interval in seconds"
    required: false
    default: "2"
  timeout:
    description: "Timeout before giving up in seconds"
    required: false
    default: "480"
runs:
  using: "composite"
  steps:
  - name: Checkout epfl-enac-deploy-action
    uses: actions/checkout@v3
    with:
      repository: EPFL-ENAC/epfl-enac-deploy-action
      ref: main
      path: epfl-enac-deploy-action

  - name: Set up Python 3.10
    uses: actions/setup-python@v4
    with:
      python-version: '3.10'

  - name: Install dependencies from requirements.txt
    shell: bash
    run: |
      pip install -r epfl-enac-deploy-action/requirements.txt

  - name: Run Python script main.py
    shell: bash
    env:
      DEPLOYMENT_SECRET: ${{ inputs.ENAC_IT4R_CD_deployment_secret }}
    run: python epfl-enac-deploy-action/main.py
      --env ${{ inputs.ENAC_IT4R_CD_environment }}
      --deployment-id ${{ inputs.ENAC_IT4R_CD_deployment_id }}
      --interval ${{ inputs.interval }}
      --timeout ${{ inputs.timeout }}
